#!/usr/bin/env bash
# A script to install and configure HAProxy on lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend Futuredev-fend
	bind *:80
	mode http
	default_backend Futuredev-bend
backend Futuredev-bend
	balance roundrobin
	server 526350-web-01 35.153.98.43 check
	server 526350-web-02 54.236.17.184 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
