#!/usr/bin/env bash

# Update package lists
sudo apt update

# Install MySQL server version 
sudo apt install mysql-server-5.7

# Start MySQL service
sudo service mysql start

# Check MySQL service status
sudo service mysql status
