#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
# Username
# User id
# Home directory path for the user

file="/etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d":" -f1,3,6;
done < "$file"
