#!/usr/bin/env bash
# Display "Best School" 10 times, but display Best School and\n
# Display Hi

i=1;

while [ $i -le 10 ];
do
	echo "Best School";
	if [ $i -eq 9 ];
	then
		echo "Hi";
	fi;
	((i++));
done
