#!/usr/bin/env bash
# Install an uncomplicated Firewall and configure ufw give exceptions to \n
# Port 22, 443 and 80

sudo apt-get update -y

sudo apt-get install ufw -y

sudo ufw enable

sudo ufw default deny incoming -y
sudo ufw default allow outgoing -y

sudo ufw allow 22/tcp

sudo ufw allow 443/tcp

sudo ufw allow 80/tcp
