#!/usr/bin/env bash
# script that configures a server(Ubuntu) with the following requirements.
# changes the following domain resolve ips
# localhost from 127.0.0.2
# facebook.com from 157.240.11.35 - 8.8.8.8


cp /etc/hosts ~/hosts.new;

echo "127.0.0.2 localhost" > ~/hosts.new;
echo "8.8.8.8  facebook.com" >> ~/hosts.new;

cp -f ~/hosts.new /etc/hosts
